### ISSUE TITLE
运行就报错

### ISSUE THREAD

**Issue by longkiGit** [WangLiquan/EWArcSoft-Swift#1]
/clang:-1: linker command failed with exit code 1 (use -v to see invocation)

**Comment by WangLiquan** [comment]
因为Xcode10 将-lstdc++.6.0.9库移除了，但是虹软并没有更新用新的依赖库。所以Xcode10运行时需要手动添加这个库。如何添加可以参考https://www.jianshu.com/p/e939e51cc3ad
